

// src/components/admin/facilitator/CurriculumTraceabilityCard.tsx

import React, { useState } from 'react';
import { 
    Clock, ShieldCheck, CheckCircle2, UserX, 
    AlertTriangle, MailWarning, DownloadCloud, ChevronDown, ChevronUp, Calendar
} from 'lucide-react';
import moment from 'moment';
import * as XLSX from 'xlsx'; // 🚀 Added XLSX import

export interface CurriculumLogData {
    id: string;
    title: string;
    moduleCode: string;
    dateLogged: string;
    notes: string;
    presentLearnerIds?: string[];
    absentLearnerIds?: string[];
    acknowledgedBy?: string[]; 
}

interface CurriculumTraceabilityCardProps {
    log: CurriculumLogData;
    roster: any[]; // The full list of enrolled learners in this cohort
}

export const CurriculumTraceabilityCard: React.FC<CurriculumTraceabilityCardProps> = ({ log, roster }) => {
    // States for our expandable sections
    const [isRegisterExpanded, setIsRegisterExpanded] = useState(false);
    const [isCatchupExpanded, setIsCatchupExpanded] = useState(false);

    const isAttendanceLinked = log.presentLearnerIds !== undefined || log.absentLearnerIds !== undefined;
    
    // Safely extract arrays (defaulting to empty arrays if undefined)
    const presentIds = log.presentLearnerIds || [];
    const absentIds = log.absentLearnerIds || [];
    
    const presentCount = presentIds.length;
    const absentCount = absentIds.length;

    // BULLETPROOF FINDER: Checks every possible ID format a learner might have
    const findLearner = (targetId: string) => {
        return roster.find(l => 
            l.id === targetId || 
            l.learnerId === targetId || 
            l.idNumber === targetId || 
            l.authUid === targetId
        );
    };

    // 🚀 EXCEL EXPORT FUNCTION
    const handleExportExcel = () => {
        // Create the data matrix
        const dataRows: any[][] = [];

        // 1. Add Header Information
        dataRows.push(["TOPIC REGISTER", log.moduleCode || "N/A"]);
        dataRows.push(["TITLE", log.title]);
        dataRows.push(["DATE LOGGED", moment(log.dateLogged).format('DD MMMM YYYY')]);
        dataRows.push(["NOTES", log.notes || "No notes recorded."]);
        dataRows.push([]); // Empty row for spacing

        // 2. Add Table Headers
        dataRows.push([
            "#", 
            "Learner Name", 
            "Email / Identity", 
            "Status", 
            "Catch-up Acknowledged"
        ]);

        // 3. Add Learner Data
        roster.forEach((l, i) => {
            const isPresent = presentIds.some(pid => pid === l.id || pid === l.learnerId || pid === l.idNumber || pid === l.authUid);
            const status = isPresent ? "Present" : "Absent";
            
            let catchupStatus = "N/A";
            if (!isPresent) {
                const pid = l.id || l.idNumber || l.learnerId;
                catchupStatus = log.acknowledgedBy?.includes(pid) ? "Yes" : "Pending";
            }

            dataRows.push([
                i + 1,
                l.fullName || 'Unknown',
                l.email || l.idNumber || 'N/A',
                status,
                catchupStatus
            ]);
        });

        dataRows.push([]);
        dataRows.push([`Document generated by mLab Assessment Centre on ${new Date().toLocaleString()}`]);

        // Convert the matrix into an Excel worksheet
        const ws = XLSX.utils.aoa_to_sheet(dataRows);

        // Adjust column widths to make it look professional
        ws['!cols'] = [
            { wch: 5 },  // #
            { wch: 30 }, // Learner Name
            { wch: 35 }, // Email / ID
            { wch: 15 }, // Status
            { wch: 25 }  // Catch-up
        ];

        // Create the workbook and append the sheet
        const wb = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(wb, ws, 'Attendance Register');

        // Generate a safe file name and download
        const safeTitle = (log.moduleCode || 'Topic').replace(/[^a-zA-Z0-9]/g, '_');
        const fileName = `Register_${safeTitle}_${moment(log.dateLogged).format('YYYYMMDD')}.xlsx`;
        
        XLSX.writeFile(wb, fileName);
    };

    return (
        <div style={{ background: 'white', borderRadius: '12px', border: '1px solid var(--mlab-border)', overflow: 'hidden', marginBottom: '20px' }}>
            
            <div style={{ padding: '16px 20px', borderBottom: '1px solid var(--mlab-border)', background: '#f8fafc', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                <div>
                    <div style={{ display: 'flex', gap: '8px', alignItems: 'center', marginBottom: '6px' }}>
                        <span style={{ fontSize: '10px', fontWeight: 700, fontFamily: 'var(--font-heading)', background: 'var(--mlab-blue)', color: 'white', padding: '2px 8px', borderRadius: '4px', letterSpacing: '0.1em' }}>
                            {log.moduleCode}
                        </span>
                        <span style={{ fontSize: '12px', color: 'var(--mlab-grey)' }}>
                            <Clock size={12} style={{ display: 'inline', marginBottom: '-2px' }}/> {moment(log.dateLogged).format('DD MMM YYYY')}
                        </span>
                    </div>
                    <h3 style={{ margin: 0, color: 'var(--mlab-blue)', fontFamily: 'var(--font-heading)', fontSize: '1.2rem', textTransform: 'uppercase' }}>
                        {log.title}
                    </h3>
                </div>

                <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                    {/* EXPORT TO EXCEL BUTTON */}
                    {isAttendanceLinked && (
                        <button 
                            onClick={handleExportExcel}
                            className="mlab-btn mlab-btn--outline-blue mlab-btn--sm" 
                            style={{ padding: '4px 8px', color: 'var(--mlab-blue)', borderColor: 'var(--mlab-blue)' }}
                            title="Export to Excel"
                        >
                            <DownloadCloud size={14} /> Export
                        </button>
                    )}

                    {/* LINKAGE STATUS BADGE */}
                    {isAttendanceLinked ? (
                        <div style={{ display: 'flex', alignItems: 'center', gap: '6px', background: 'var(--mlab-green-bg)', color: 'var(--mlab-green-dark)', padding: '6px 12px', borderRadius: '20px', fontSize: '0.75rem', fontWeight: 'bold' }}>
                            <ShieldCheck size={16} /> Attendance Linked
                        </div>
                    ) : (
                        <div style={{ display: 'flex', alignItems: 'center', gap: '6px', background: '#fffbeb', color: '#d97706', border: '1px solid #fde68a', padding: '6px 12px', borderRadius: '20px', fontSize: '0.75rem', fontWeight: 'bold' }}>
                            <Clock size={16} /> Pending Daily Register
                        </div>
                    )}
                </div>
            </div>

            <div style={{ padding: '20px' }}>
                <p style={{ fontSize: '0.9rem', color: '#475569', margin: '0 0 20px 0', lineHeight: 1.6 }}>
                    <strong>Facilitator Notes:</strong> {log.notes}
                </p>

                {isAttendanceLinked && (
                    <>
                        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px', marginBottom: '20px' }}>
                            <div style={{ background: '#f0fdf4', border: '1px solid #bbf7d0', padding: '12px', borderRadius: '8px', display: 'flex', alignItems: 'center', gap: '12px' }}>
                                <CheckCircle2 size={24} color="#16a34a" />
                                <div>
                                    <div style={{ fontSize: '0.75rem', fontWeight: 'bold', color: '#166534', textTransform: 'uppercase' }}>Present for Topic</div>
                                    <div style={{ fontSize: '1.2rem', fontWeight: 800, color: '#15803d' }}>{presentCount} Learners</div>
                                </div>
                            </div>
                            <div style={{ background: '#fef2f2', border: '1px solid #fecaca', padding: '12px', borderRadius: '8px', display: 'flex', alignItems: 'center', gap: '12px' }}>
                                <UserX size={24} color="#dc2626" />
                                <div>
                                    <div style={{ fontSize: '0.75rem', fontWeight: 'bold', color: '#991b1b', textTransform: 'uppercase' }}>Absent / Missed Topic</div>
                                    <div style={{ fontSize: '1.2rem', fontWeight: 800, color: '#b91c1c' }}>{absentCount} Learners</div>
                                </div>
                            </div>
                        </div>

                        {/* ── 🚀 EXPANDABLE ACTION REQUIRED LIST ── */}
                        {absentIds.length > 0 && (
                            <div style={{ borderTop: '2px dashed var(--mlab-border)', paddingTop: '20px', marginBottom: '20px' }}>
                                <button 
                                    onClick={() => setIsCatchupExpanded(!isCatchupExpanded)}
                                    style={{ display: 'flex', width: '100%', alignItems: 'center', justifyContent: 'space-between', background: 'transparent', border: 'none', cursor: 'pointer', padding: '0 0 12px 0', color: '#dc2626' }}
                                >
                                    <h4 style={{ margin: 0, display: 'flex', alignItems: 'center', gap: '6px', fontSize: '0.9rem', textTransform: 'uppercase', fontFamily: 'var(--font-heading)' }}>
                                        <AlertTriangle size={16} /> Catch-up Monitoring Required ({absentCount})
                                    </h4>
                                    {isCatchupExpanded ? <ChevronUp size={18} /> : <ChevronDown size={18} />}
                                </button>
                                
                                {isCatchupExpanded && (
                                    <div className="animate-fade-in" style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
                                        {absentIds.map((pid: string) => {
                                            const learner = findLearner(pid);
                                            const hasAcknowledged = log.acknowledgedBy?.includes(pid);
                                            const displayName = learner ? learner.fullName : `Unknown ID (${pid.substring(0,6)})`;
                                            const displayEmail = learner ? learner.email : 'No profile found';
                                            
                                            return (
                                                <div key={pid} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: '#f8fafc', padding: '10px 16px', borderRadius: '6px', borderLeft: `4px solid ${hasAcknowledged ? '#16a34a' : '#f59e0b'}` }}>
                                                    <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                                                        <div style={{ width: '32px', height: '32px', background: 'var(--mlab-light-blue)', color: 'var(--mlab-blue)', display: 'flex', alignItems: 'center', justifyContent: 'center', borderRadius: '50%', fontWeight: 'bold', fontSize: '12px' }}>
                                                            {displayName.charAt(0)}
                                                        </div>
                                                        <div>
                                                            <div style={{ fontSize: '0.9rem', fontWeight: 600, color: 'var(--mlab-blue)' }}>{displayName}</div>
                                                            <div style={{ fontSize: '0.75rem', color: 'var(--mlab-grey)' }}>{displayEmail}</div>
                                                        </div>
                                                    </div>

                                                    {hasAcknowledged ? (
                                                        <div style={{ display: 'flex', alignItems: 'center', gap: '4px', fontSize: '0.75rem', fontWeight: 'bold', color: '#16a34a' }}>
                                                            <CheckCircle2 size={14} /> Catch-up Acknowledged
                                                        </div>
                                                    ) : (
                                                        <button className="mlab-btn mlab-btn--outline-blue mlab-btn--sm" style={{ color: '#d97706', borderColor: '#d97706', padding: '4px 8px' }}>
                                                            <MailWarning size={14} /> Ping Reminder
                                                        </button>
                                                    )}
                                                </div>
                                            );
                                        })}
                                    </div>
                                )}
                            </div>
                        )}

                        {/* ── EXPANDABLE ATTENDANCE REGISTER ── */}
                        <div style={{ borderTop: '1px solid var(--mlab-border)', paddingTop: '15px' }}>
                            <button 
                                onClick={() => setIsRegisterExpanded(!isRegisterExpanded)}
                                style={{ display: 'flex', width: '100%', alignItems: 'center', justifyContent: 'space-between', background: 'transparent', border: 'none', cursor: 'pointer', padding: '8px 0', color: 'var(--mlab-blue)', fontWeight: 600 }}
                            >
                                <span style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                                    <Calendar size={16} /> {isRegisterExpanded ? 'Hide' : 'View'} Full Class Register
                                </span>
                                {isRegisterExpanded ? <ChevronUp size={18} /> : <ChevronDown size={18} />}
                            </button>

                            {isRegisterExpanded && (
                                <div className="animate-fade-in" style={{ marginTop: '15px', display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px', background: '#f8fafc', padding: '15px', borderRadius: '8px', border: '1px solid var(--mlab-border)' }}>
                                    {/* Present Column */}
                                    <div>
                                        <h4 style={{ margin: '0 0 12px 0', color: '#166534', display: 'flex', alignItems: 'center', gap: '6px', fontSize: '0.85rem', textTransform: 'uppercase', fontFamily: 'var(--font-heading)' }}>
                                            <CheckCircle2 size={14} /> Present Learners
                                        </h4>
                                        <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
                                            {presentIds.length > 0 ? presentIds.map((pid: string) => {
                                                const learner = findLearner(pid);
                                                return (
                                                    <div key={pid} style={{ display: 'flex', alignItems: 'center', gap: '8px', background: 'white', padding: '6px 10px', borderRadius: '4px', border: '1px solid #e2e8f0' }}>
                                                        <span style={{ fontSize: '0.8rem', fontWeight: 500, color: '#334155' }}>
                                                            {learner ? learner.fullName : `Unknown Learner (${pid.substring(0,6)})`}
                                                        </span>
                                                    </div>
                                                );
                                            }) : <span style={{ fontSize: '0.8rem', color: 'var(--mlab-grey)', fontStyle: 'italic' }}>No learners present.</span>}
                                        </div>
                                    </div>

                                    {/* Absent Column */}
                                    <div>
                                        <h4 style={{ margin: '0 0 12px 0', color: '#dc2626', display: 'flex', alignItems: 'center', gap: '6px', fontSize: '0.85rem', textTransform: 'uppercase', fontFamily: 'var(--font-heading)' }}>
                                            <UserX size={14} /> Absent Learners
                                        </h4>
                                        <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
                                            {absentIds.length > 0 ? absentIds.map((pid: string) => {
                                                const learner = findLearner(pid);
                                                return (
                                                    <div key={pid} style={{ display: 'flex', alignItems: 'center', gap: '8px', background: 'white', padding: '6px 10px', borderRadius: '4px', border: '1px solid #e2e8f0' }}>
                                                        <span style={{ fontSize: '0.8rem', fontWeight: 500, color: '#334155' }}>
                                                            {learner ? learner.fullName : `Unknown Learner (${pid.substring(0,6)})`}
                                                        </span>
                                                    </div>
                                                );
                                            }) : <span style={{ fontSize: '0.8rem', color: 'var(--mlab-grey)', fontStyle: 'italic' }}>No learners absent.</span>}
                                        </div>
                                    </div>
                                </div>
                            )}
                        </div>
                    </>
                )}
            </div>
        </div>
    );
};


// // src/components/admin/facilitator/CurriculumTraceabilityCard.tsx

// import React, { useState } from 'react';
// import {
//     Clock, ShieldCheck, CheckCircle2, UserX,
//     AlertTriangle, MailWarning, Printer, ChevronDown, ChevronUp, Calendar
// } from 'lucide-react';
// import moment from 'moment';

// export interface CurriculumLogData {
//     id: string;
//     title: string;
//     moduleCode: string;
//     dateLogged: string;
//     notes: string;
//     presentLearnerIds?: string[];
//     absentLearnerIds?: string[];
//     acknowledgedBy?: string[];
// }

// interface CurriculumTraceabilityCardProps {
//     log: CurriculumLogData;
//     roster: any[]; // The full list of enrolled learners in this cohort
// }

// export const CurriculumTraceabilityCard: React.FC<CurriculumTraceabilityCardProps> = ({ log, roster }) => {
//     const [isRegisterExpanded, setIsRegisterExpanded] = useState(false);

//     const isAttendanceLinked = log.presentLearnerIds !== undefined || log.absentLearnerIds !== undefined;

//     // Safely extract arrays (defaulting to empty arrays if undefined)
//     const presentIds = log.presentLearnerIds || [];
//     const absentIds = log.absentLearnerIds || [];

//     const presentCount = presentIds.length;
//     const absentCount = absentIds.length;

//     // 🚀 BULLETPROOF FINDER: Checks every possible ID format a learner might have
//     const findLearner = (targetId: string) => {
//         return roster.find(l =>
//             l.id === targetId ||
//             l.learnerId === targetId ||
//             l.idNumber === targetId ||
//             l.authUid === targetId
//         );
//     };

//     const handlePrint = () => {
//         const printWindow = window.open('', '_blank');
//         if (!printWindow) return;

//         const html = `
//             <!DOCTYPE html>
//             <html>
//                 <head>
//                     <title>Attendance Register - ${log.moduleCode}</title>
//                     <style>
//                         body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 30px; color: #1e293b; line-height: 1.5; }
//                         .header { border-bottom: 2px solid #0f172a; padding-bottom: 15px; margin-bottom: 25px; }
//                         .header h1 { color: #0f172a; font-size: 22px; text-transform: uppercase; margin: 0 0 5px 0; letter-spacing: 0.05em; }
//                         .header h2 { color: #64748b; font-size: 14px; margin: 0; font-weight: 500; }
//                         .notes { background: #f8fafc; border-left: 4px solid #94c73d; padding: 12px 15px; margin-bottom: 25px; font-size: 13px; }
//                         table { width: 100%; border-collapse: collapse; font-size: 12px; }
//                         th, td { border: 1px solid #cbd5e1; padding: 10px 12px; text-align: left; }
//                         th { background-color: #f1f5f9; font-weight: bold; text-transform: uppercase; color: #475569; letter-spacing: 0.05em; }
//                         tr:nth-child(even) { background-color: #f8fafc; }
//                         .present { color: #16a34a; font-weight: bold; }
//                         .absent { color: #dc2626; font-weight: bold; }
//                     </style>
//                 </head>
//                 <body>
//                     <div class="header">
//                         <h1>Topic Register: ${log.moduleCode}</h1>
//                         <h2>${log.title} | ${moment(log.dateLogged).format('DD MMMM YYYY')}</h2>
//                     </div>
                    
//                     <div class="notes">
//                         <strong>Facilitator Notes:</strong><br/>
//                         ${log.notes || "No notes recorded."}
//                     </div>
                    
//                     <table>
//                         <thead>
//                             <tr>
//                                 <th width="40">#</th>
//                                 <th>Learner Name</th>
//                                 <th>Email / Identity</th>
//                                 <th width="100">Status</th>
//                                 <th width="150">Signature</th>
//                             </tr>
//                         </thead>
//                         <tbody>
//                             ${roster.map((l, i) => {
//             // Robust check for printing
//             const isPresent = presentIds.some(pid => pid === l.id || pid === l.learnerId || pid === l.idNumber || pid === l.authUid);
//             return `
//                                     <tr>
//                                         <td>${i + 1}</td>
//                                         <td><strong>${l.fullName || 'Unknown'}</strong></td>
//                                         <td>${l.email || l.idNumber || 'N/A'}</td>
//                                         <td class="${isPresent ? 'present' : 'absent'}">${isPresent ? 'Present' : 'Absent'}</td>
//                                         <td></td>
//                                     </tr>
//                                 `;
//         }).join('')}
//                         </tbody>
//                     </table>

//                     <div style="margin-top: 40px; font-size: 12px; color: #64748b;">
//                         <em>Document generated by mLab Assessment Centre on ${new Date().toLocaleString()}</em>
//                     </div>
//                 </body>
//             </html>
//         `;

//         printWindow.document.write(html);
//         printWindow.document.close();
//         printWindow.focus();
//         setTimeout(() => { printWindow.print(); printWindow.close(); }, 250);
//     };

//     return (
//         <div style={{ background: 'white', borderRadius: '12px', border: '1px solid var(--mlab-border)', overflow: 'hidden', marginBottom: '20px' }}>

//             <div style={{ padding: '16px 20px', borderBottom: '1px solid var(--mlab-border)', background: '#f8fafc', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
//                 <div>
//                     <div style={{ display: 'flex', gap: '8px', alignItems: 'center', marginBottom: '6px' }}>
//                         <span style={{ fontSize: '10px', fontWeight: 700, fontFamily: 'var(--font-heading)', background: 'var(--mlab-blue)', color: 'white', padding: '2px 8px', borderRadius: '4px', letterSpacing: '0.1em' }}>
//                             {log.moduleCode}
//                         </span>
//                         <span style={{ fontSize: '12px', color: 'var(--mlab-grey)' }}>
//                             <Clock size={12} style={{ display: 'inline', marginBottom: '-2px' }} /> {moment(log.dateLogged).format('DD MMM YYYY')}
//                         </span>
//                     </div>
//                     <h3 style={{ margin: 0, color: 'var(--mlab-blue)', fontFamily: 'var(--font-heading)', fontSize: '1.2rem', textTransform: 'uppercase' }}>
//                         {log.title}
//                     </h3>
//                 </div>

//                 <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
//                     {isAttendanceLinked && (
//                         <button
//                             onClick={handlePrint}
//                             className="mlab-btn mlab-btn--outline-blue mlab-btn--sm"
//                             style={{ padding: '4px 8px', color: 'var(--mlab-blue)', borderColor: 'var(--mlab-blue)' }}
//                             title="Print Register"
//                         >
//                             <Printer size={14} /> Print
//                         </button>
//                     )}

//                     {isAttendanceLinked ? (
//                         <div style={{ display: 'flex', alignItems: 'center', gap: '6px', background: 'var(--mlab-green-bg)', color: 'var(--mlab-green-dark)', padding: '6px 12px', borderRadius: '20px', fontSize: '0.75rem', fontWeight: 'bold' }}>
//                             <ShieldCheck size={16} /> Attendance Linked
//                         </div>
//                     ) : (
//                         <div style={{ display: 'flex', alignItems: 'center', gap: '6px', background: '#fffbeb', color: '#d97706', border: '1px solid #fde68a', padding: '6px 12px', borderRadius: '20px', fontSize: '0.75rem', fontWeight: 'bold' }}>
//                             <Clock size={16} /> Pending Daily Register
//                         </div>
//                     )}
//                 </div>
//             </div>

//             <div style={{ padding: '20px' }}>
//                 <p style={{ fontSize: '0.9rem', color: '#475569', margin: '0 0 20px 0', lineHeight: 1.6 }}>
//                     <strong>Facilitator Notes:</strong> {log.notes}
//                 </p>

//                 {isAttendanceLinked && (
//                     <>
//                         <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px', marginBottom: '20px' }}>
//                             <div style={{ background: '#f0fdf4', border: '1px solid #bbf7d0', padding: '12px', borderRadius: '8px', display: 'flex', alignItems: 'center', gap: '12px' }}>
//                                 <CheckCircle2 size={24} color="#16a34a" />
//                                 <div>
//                                     <div style={{ fontSize: '0.75rem', fontWeight: 'bold', color: '#166534', textTransform: 'uppercase' }}>Present for Topic</div>
//                                     <div style={{ fontSize: '1.2rem', fontWeight: 800, color: '#15803d' }}>{presentCount} Learners</div>
//                                 </div>
//                             </div>
//                             <div style={{ background: '#fef2f2', border: '1px solid #fecaca', padding: '12px', borderRadius: '8px', display: 'flex', alignItems: 'center', gap: '12px' }}>
//                                 <UserX size={24} color="#dc2626" />
//                                 <div>
//                                     <div style={{ fontSize: '0.75rem', fontWeight: 'bold', color: '#991b1b', textTransform: 'uppercase' }}>Absent / Missed Topic</div>
//                                     <div style={{ fontSize: '1.2rem', fontWeight: 800, color: '#b91c1c' }}>{absentCount} Learners</div>
//                                 </div>
//                             </div>
//                         </div>

//                         {/* ACTION REQUIRED LIST */}
//                         {absentIds.length > 0 && (
//                             <div style={{ borderTop: '2px dashed var(--mlab-border)', paddingTop: '20px', marginBottom: '20px' }}>
//                                 <h4 style={{ margin: '0 0 12px 0', color: '#dc2626', display: 'flex', alignItems: 'center', gap: '6px', fontSize: '0.9rem', textTransform: 'uppercase', fontFamily: 'var(--font-heading)' }}>
//                                     <AlertTriangle size={16} /> Catch-up Monitoring Required
//                                 </h4>

//                                 <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
//                                     {absentIds.map((pid: string) => {
//                                         const learner = findLearner(pid);
//                                         const hasAcknowledged = log.acknowledgedBy?.includes(pid);
//                                         const displayName = learner ? learner.fullName : `Unknown ID (${pid.substring(0, 6)})`;
//                                         const displayEmail = learner ? learner.email : 'No profile found';

//                                         return (
//                                             <div key={pid} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: '#f8fafc', padding: '10px 16px', borderRadius: '6px', borderLeft: `4px solid ${hasAcknowledged ? '#16a34a' : '#f59e0b'}` }}>
//                                                 <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
//                                                     <div style={{ width: '32px', height: '32px', background: 'var(--mlab-light-blue)', color: 'var(--mlab-blue)', display: 'flex', alignItems: 'center', justifyContent: 'center', borderRadius: '50%', fontWeight: 'bold', fontSize: '12px' }}>
//                                                         {displayName.charAt(0)}
//                                                     </div>
//                                                     <div>
//                                                         <div style={{ fontSize: '0.9rem', fontWeight: 600, color: 'var(--mlab-blue)' }}>{displayName}</div>
//                                                         <div style={{ fontSize: '0.75rem', color: 'var(--mlab-grey)' }}>{displayEmail}</div>
//                                                     </div>
//                                                 </div>

//                                                 {hasAcknowledged ? (
//                                                     <div style={{ display: 'flex', alignItems: 'center', gap: '4px', fontSize: '0.75rem', fontWeight: 'bold', color: '#16a34a' }}>
//                                                         <CheckCircle2 size={14} /> Catch-up Acknowledged
//                                                     </div>
//                                                 ) : (
//                                                     <button className="mlab-btn mlab-btn--outline-blue mlab-btn--sm" style={{ color: '#d97706', borderColor: '#d97706', padding: '4px 8px' }}>
//                                                         <MailWarning size={14} /> Ping Reminder
//                                                     </button>
//                                                 )}
//                                             </div>
//                                         );
//                                     })}
//                                 </div>
//                             </div>
//                         )}

//                         {/* EXPANDABLE ATTENDANCE REGISTER */}
//                         <div style={{ borderTop: '1px solid var(--mlab-border)', paddingTop: '15px' }}>
//                             <button
//                                 onClick={() => setIsRegisterExpanded(!isRegisterExpanded)}
//                                 style={{ display: 'flex', width: '100%', alignItems: 'center', justifyContent: 'space-between', background: 'transparent', border: 'none', cursor: 'pointer', padding: '8px 0', color: 'var(--mlab-blue)', fontWeight: 600 }}
//                             >
//                                 <span style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
//                                     <Calendar size={16} /> {isRegisterExpanded ? 'Hide' : 'View'} Full Class Register
//                                 </span>
//                                 {isRegisterExpanded ? <ChevronUp size={18} /> : <ChevronDown size={18} />}
//                             </button>

//                             {isRegisterExpanded && (
//                                 <div className="animate-fade-in" style={{ marginTop: '15px', display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px', background: '#f8fafc', padding: '15px', borderRadius: '8px', border: '1px solid var(--mlab-border)' }}>
//                                     {/* Present Column */}
//                                     <div>
//                                         <h4 style={{ margin: '0 0 12px 0', color: '#166534', display: 'flex', alignItems: 'center', gap: '6px', fontSize: '0.85rem', textTransform: 'uppercase', fontFamily: 'var(--font-heading)' }}>
//                                             <CheckCircle2 size={14} /> Present Learners
//                                         </h4>
//                                         <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
//                                             {presentIds.length > 0 ? presentIds.map((pid: string) => {
//                                                 const learner = findLearner(pid);
//                                                 return (
//                                                     <div key={pid} style={{ display: 'flex', alignItems: 'center', gap: '8px', background: 'white', padding: '6px 10px', borderRadius: '4px', border: '1px solid #e2e8f0' }}>
//                                                         <span style={{ fontSize: '0.8rem', fontWeight: 500, color: '#334155' }}>
//                                                             {learner ? learner.fullName : `Unknown Learner (${pid.substring(0, 6)})`}
//                                                         </span>
//                                                     </div>
//                                                 );
//                                             }) : <span style={{ fontSize: '0.8rem', color: 'var(--mlab-grey)', fontStyle: 'italic' }}>No learners present.</span>}
//                                         </div>
//                                     </div>

//                                     {/* Absent Column */}
//                                     <div>
//                                         <h4 style={{ margin: '0 0 12px 0', color: '#dc2626', display: 'flex', alignItems: 'center', gap: '6px', fontSize: '0.85rem', textTransform: 'uppercase', fontFamily: 'var(--font-heading)' }}>
//                                             <UserX size={14} /> Absent Learners
//                                         </h4>
//                                         <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
//                                             {absentIds.length > 0 ? absentIds.map((pid: string) => {
//                                                 const learner = findLearner(pid);
//                                                 return (
//                                                     <div key={pid} style={{ display: 'flex', alignItems: 'center', gap: '8px', background: 'white', padding: '6px 10px', borderRadius: '4px', border: '1px solid #e2e8f0' }}>
//                                                         <span style={{ fontSize: '0.8rem', fontWeight: 500, color: '#334155' }}>
//                                                             {learner ? learner.fullName : `Unknown Learner (${pid.substring(0, 6)})`}
//                                                         </span>
//                                                     </div>
//                                                 );
//                                             }) : <span style={{ fontSize: '0.8rem', color: 'var(--mlab-grey)', fontStyle: 'italic' }}>No learners absent.</span>}
//                                         </div>
//                                     </div>
//                                 </div>
//                             )}
//                         </div>
//                     </>
//                 )}
//             </div>
//         </div>
//     );
// };



// // // src/components/admin/facilitator/CurriculumTraceabilityCard.tsx

// // import React from 'react';
// // import {
// //     Clock, ShieldCheck, CheckCircle2, UserX,
// //     AlertTriangle, MailWarning
// // } from 'lucide-react';
// // import moment from 'moment';

// // // Define the exact shape of the data we expect
// // export interface CurriculumLogData {
// //     id: string;
// //     title: string;
// //     moduleCode: string;
// //     dateLogged: string;
// //     notes: string;
// //     presentLearnerIds?: string[];
// //     absentLearnerIds?: string[];
// //     acknowledgedBy?: string[];
// // }

// // interface CurriculumTraceabilityCardProps {
// //     log: CurriculumLogData;
// //     roster: any[]; // The full list of learners in this cohort
// // }

// // export const CurriculumTraceabilityCard: React.FC<CurriculumTraceabilityCardProps> = ({ log, roster }) => {
// //     // Determine the state of the "Handshake"
// //     const isAttendanceLinked = log.presentLearnerIds !== undefined || log.absentLearnerIds !== undefined;

// //     // Map IDs to actual learner objects for display
// //     const absentLearners = roster.filter(l => log.absentLearnerIds?.includes(l.id || l.idNumber));
// //     const presentCount = log.presentLearnerIds?.length || 0;
// //     const absentCount = log.absentLearnerIds?.length || 0;

// //     return (
// //         <div style={{ background: 'white', borderRadius: '12px', border: '1px solid var(--mlab-border)', overflow: 'hidden', marginBottom: '20px' }}>

// //             {/* ── HEADER ── */}
// //             <div style={{ padding: '16px 20px', borderBottom: '1px solid var(--mlab-border)', background: '#f8fafc', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
// //                 <div>
// //                     <div style={{ display: 'flex', gap: '8px', alignItems: 'center', marginBottom: '6px' }}>
// //                         <span style={{ fontSize: '10px', fontWeight: 700, fontFamily: 'var(--font-heading)', background: 'var(--mlab-blue)', color: 'white', padding: '2px 8px', borderRadius: '4px', letterSpacing: '0.1em' }}>
// //                             {log.moduleCode}
// //                         </span>
// //                         <span style={{ fontSize: '12px', color: 'var(--mlab-grey)' }}>
// //                             <Clock size={12} style={{ display: 'inline', marginBottom: '-2px' }} /> {moment(log.dateLogged).format('DD MMM YYYY')}
// //                         </span>
// //                     </div>
// //                     <h3 style={{ margin: 0, color: 'var(--mlab-blue)', fontFamily: 'var(--font-heading)', fontSize: '1.2rem', textTransform: 'uppercase' }}>
// //                         {log.title}
// //                     </h3>
// //                 </div>

// //                 {/* LINKAGE STATUS BADGE */}
// //                 {isAttendanceLinked ? (
// //                     <div style={{ display: 'flex', alignItems: 'center', gap: '6px', background: 'var(--mlab-green-bg)', color: 'var(--mlab-green-dark)', padding: '6px 12px', borderRadius: '20px', fontSize: '0.75rem', fontWeight: 'bold' }}>
// //                         <ShieldCheck size={16} /> Attendance Linked
// //                     </div>
// //                 ) : (
// //                     <div style={{ display: 'flex', alignItems: 'center', gap: '6px', background: '#fffbeb', color: '#d97706', border: '1px solid #fde68a', padding: '6px 12px', borderRadius: '20px', fontSize: '0.75rem', fontWeight: 'bold' }}>
// //                         <Clock size={16} /> Pending Daily Register
// //                     </div>
// //                 )}
// //             </div>

// //             {/* ── BODY ── */}
// //             <div style={{ padding: '20px' }}>
// //                 <p style={{ fontSize: '0.9rem', color: '#475569', margin: '0 0 20px 0', lineHeight: 1.6 }}>
// //                     <strong>Facilitator Notes:</strong> {log.notes}
// //                 </p>

// //                 {/* ── TRACEABILITY STATS ── */}
// //                 {isAttendanceLinked && (
// //                     <>
// //                         <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px', marginBottom: '20px' }}>
// //                             <div style={{ background: '#f0fdf4', border: '1px solid #bbf7d0', padding: '12px', borderRadius: '8px', display: 'flex', alignItems: 'center', gap: '12px' }}>
// //                                 <CheckCircle2 size={24} color="#16a34a" />
// //                                 <div>
// //                                     <div style={{ fontSize: '0.75rem', fontWeight: 'bold', color: '#166534', textTransform: 'uppercase' }}>Present for Topic</div>
// //                                     <div style={{ fontSize: '1.2rem', fontWeight: 800, color: '#15803d' }}>{presentCount} Learners</div>
// //                                 </div>
// //                             </div>
// //                             <div style={{ background: '#fef2f2', border: '1px solid #fecaca', padding: '12px', borderRadius: '8px', display: 'flex', alignItems: 'center', gap: '12px' }}>
// //                                 <UserX size={24} color="#dc2626" />
// //                                 <div>
// //                                     <div style={{ fontSize: '0.75rem', fontWeight: 'bold', color: '#991b1b', textTransform: 'uppercase' }}>Absent / Missed Topic</div>
// //                                     <div style={{ fontSize: '1.2rem', fontWeight: 800, color: '#b91c1c' }}>{absentCount} Learners</div>
// //                                 </div>
// //                             </div>
// //                         </div>

// //                         {/* ── ACTION REQUIRED: ABSENT LEARNER LIST ── */}
// //                         {absentLearners.length > 0 && (
// //                             <div style={{ borderTop: '2px dashed var(--mlab-border)', paddingTop: '20px' }}>
// //                                 <h4 style={{ margin: '0 0 12px 0', color: '#dc2626', display: 'flex', alignItems: 'center', gap: '6px', fontSize: '0.9rem', textTransform: 'uppercase', fontFamily: 'var(--font-heading)' }}>
// //                                     <AlertTriangle size={16} /> Catch-up Monitoring Required
// //                                 </h4>

// //                                 <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
// //                                     {absentLearners.map((learner: any) => {
// //                                         // Handle both legacy string IDs and standardized objects just in case
// //                                         const learnerId = learner.id || learner.idNumber;
// //                                         const hasAcknowledged = log.acknowledgedBy?.includes(learnerId);

// //                                         return (
// //                                             <div key={learnerId} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: '#f8fafc', padding: '10px 16px', borderRadius: '6px', borderLeft: `4px solid ${hasAcknowledged ? '#16a34a' : '#f59e0b'}` }}>
// //                                                 <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
// //                                                     <div style={{ width: '32px', height: '32px', background: 'var(--mlab-light-blue)', color: 'var(--mlab-blue)', display: 'flex', alignItems: 'center', justifyContent: 'center', borderRadius: '50%', fontWeight: 'bold', fontSize: '12px' }}>
// //                                                         {learner.fullName?.charAt(0) || '?'}
// //                                                     </div>
// //                                                     <div>
// //                                                         <div style={{ fontSize: '0.9rem', fontWeight: 600, color: 'var(--mlab-blue)' }}>{learner.fullName || 'Unknown Learner'}</div>
// //                                                         <div style={{ fontSize: '0.75rem', color: 'var(--mlab-grey)' }}>{learner.email || 'No email provided'}</div>
// //                                                     </div>
// //                                                 </div>

// //                                                 {hasAcknowledged ? (
// //                                                     <div style={{ display: 'flex', alignItems: 'center', gap: '4px', fontSize: '0.75rem', fontWeight: 'bold', color: '#16a34a' }}>
// //                                                         <CheckCircle2 size={14} /> Catch-up Acknowledged
// //                                                     </div>
// //                                                 ) : (
// //                                                     <button className="mlab-btn mlab-btn--outline-blue mlab-btn--sm" style={{ color: '#d97706', borderColor: '#d97706', padding: '4px 8px' }}>
// //                                                         <MailWarning size={14} /> Ping Reminder
// //                                                     </button>
// //                                                 )}
// //                                             </div>
// //                                         );
// //                                     })}
// //                                 </div>
// //                             </div>
// //                         )}
// //                     </>
// //                 )}
// //             </div>
// //         </div>
// //     );
// // };